
* DONE handle errors in verifications
  Catch conditions that accure during verification
  and generate a verification result that has nice information about what accured

* DONE integrate quickcheck-like verification
  Establish a means to run verifications against values generated by a generator stream
  It can probably look something like this:

  (quickcheck (subject (some-generator-expression))
    (verify subject verifier))

  It would not notify success for every succeeded verification but collect all
  results and display all failures. It would pick the very first failure for
  each failed verifier and display only these.

  There should be a parameter to configure the amount of samples used per
  verification run

* FEATURE filter verifications by meta data
  Add a possibility to exclude/include verifications based on meta data.
  There should be two ways to configure filters
  1) via a paramater
  2) environment variables
* DONE add tests for console reporter
* FEATURE quickcheck output
  Add information about how much iterations it took to find a falsification
* FEATURE add FAILURE
  Instead of ID for failures write FAILURE. This is easily grepable
