(use veritas-console veritas-quickcheck data-generators)

;; general settings
(use-documentation-formatter)

;; how many examples are generated by quickcheck
(current-sample-size 100)

(group "quickcheck"
  (define (my-reverse ls)
    (fold cons '() ls))

  (group "my-reverse"
     (quickcheck (ls (with-size (1 . 5)
                                (gen-list-of (cut between gen-fixnum 0 10))))
        (let ((reversed (my-reverse ls)))
           (verify (my-reverse reversed) (is ls) "is reversable")
           (verify (length reversed) (is (length ls)) "preserves length")
           (verify reversed (is (reverse ls)) "works like the builtin")))))

(group "is verifier"
  (verify "single line" (is "single line"))
  (verify "multiline\ntext" (is "multiline\ntaxi\nstation") "handles differences in strings nicely")
  (verify #t)
  (verify 3 (is > 0)))

(group "pending"
  (pending "Need to fix other stuff first"
     (verify (error "I will never be executed"))))


(group "handling errors"
  (verify (error "It handles errors")))
